import styles from "./index.module.scss";
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import Header from "~/components/Header";
import Search from "~/components/Search";
import AddModal from "~/components/AddModal";
import PinGrid from "~/components/PinGrid";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Picterest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Search />
      <AddModal />
      <PinGrid />
    </>
  );
};

export default Home;

