import { type NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import Filters from "~/components/Filters";
const Header = dynamic(() => import("~/components/Header"));
const Search = dynamic(() => import("~/components/Search"));
const AddModal = dynamic(() => import("~/components/AddModal"));
const PinGrid = dynamic(() => import("~/components/PinGrid"));

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Picterest</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Search />
            <Filters />
            <AddModal />
            <PinGrid />
        </>
    );
};

export default Home;
